"""Bayesian Evidence Streams — the first task.

See research/SPEC-000-derivative-probe.md and research/SPEC-001-tasks-and-data.md.

A stream is generated by forward-simulating Bayesian belief update. One of K
hypotheses is true; S sources emit tokens, each informative (drawn from a
hypothesis-conditional distribution) with probability equal to its hidden
reliability, else a decoy drawn from the marginal. Reliability can flip late.
All latents are therefore known exactly.

The defining property (anti-legibility, Transform 3 / SPEC-001): because the
update is `posterior ∝ likelihood · prior`, the belief-move of a given
(token, source) pair depends on the ENTIRE preceding posterior. The same token
emitted at different points moves belief differently. This is what makes the
task belief-tracking rather than grammar-reading, and is verified by
test_belief_move_is_history_dependent.
"""
from __future__ import annotations
from dataclasses import dataclass, field
import numpy as np


@dataclass
class StreamSample:
    """One generated evidence stream with full ground-truth latents.

    Shapes: T = seq_len (fixed), K = num_hypotheses, S = num_sources.
    """
    tokens: np.ndarray            # int[T]
    answer: int                   # argmax hypothesis (label)
    # --- level features (trivial probe targets; the control) ---
    posterior: np.ndarray         # float[T, K]
    entropy: np.ndarray           # float[T]
    # --- derivative features (THE probe targets) ---
    belief_move: np.ndarray       # float[T]   per-token true belief move
    d_conf: np.ndarray            # float[T]   topmass[t]-topmass[t-1]
    dd_conf: np.ndarray           # float[T]   second difference of topmass
    # --- routing features ---
    source_idx: np.ndarray        # int[T]     observed source id, -1 for PAD
    source_trust: np.ndarray      # float[T, S]
    # --- ground-truth indices for decisive-token recall ---
    decisive_idx: np.ndarray      # int[T]   1 at thresholded belief-move steps
    # --- block boundaries for sparse attention ---
    block_boundaries: np.ndarray  # int[num_blocks+1]
    metadata: dict = field(default_factory=dict)


# Reserved vocab id for padding (emitted after the natural end of the stream).
PAD_TOKEN = 0


class BayesianEvidenceStream:
    """Generates Bayesian Evidence Streams.

    Args:
        num_hypotheses: K.
        num_sources: S. Each source has a hidden reliability drawn per stream.
        seq_len: fixed T. The stream's natural length is drawn <= T and padded.
        vocab_size: total vocab including PAD. The informative vocab is the
            remaining ids; hypothesis-conditional likelihoods live there.
        seed: deterministic.
    """

    def __init__(
        self,
        num_hypotheses: int = 4,
        num_sources: int = 3,
        seq_len: int = 512,
        vocab_size: int = 64,
        seed: int = 0,
    ):
        assert num_hypotheses >= 2
        assert num_sources >= 1
        assert vocab_size >= num_hypotheses + 2  # room for PAD + decoys + signal
        self.K = num_hypotheses
        self.S = num_sources
        self.T = seq_len
        self.vocab_size = vocab_size
        self.seed = seed
        rng = np.random.default_rng(seed)
        info_vocab = vocab_size - 1
        eps_scale = 0.20
        eps = rng.normal(0.0, eps_scale, size=(info_vocab, num_hypotheses))
        likelihood = np.exp(eps)
        self._likelihood = likelihood / likelihood.sum(axis=0, keepdims=True)
        self._marginal = self._likelihood.mean(axis=1)

    def generate(self, seed: int | None = None) -> StreamSample:
        rng = np.random.default_rng(self.seed if seed is None else seed)
        K, S, T, V = self.K, self.S, self.T, self.vocab_size
        info_vocab = V - 1  # exclude PAD
        assert info_vocab >= K, "need at least K informative tokens"

        # --- hidden state for this stream ---
        h_star = int(rng.integers(K))                      # true hypothesis
        # per-source reliability, drawn Beta; mapped into [0.2, 0.95]
        r = 0.2 + 0.75 * rng.beta(2.0, 2.0, size=S)

        L = self._likelihood
        marginal = self._marginal

        # --- reliability reversal schedule ---
        # Multiple sources can flip, at staggered late steps, with a chance of
        # flipping back. Sustained reliability dynamics — not a single event —
        # keep belief contested throughout the stream (prevents early collapse).
        n_flips = int(rng.integers(1, max(2, S)))
        flip_srcs = rng.choice(S, size=n_flips, replace=False)
        flip_steps = sorted(int(x) for x in rng.integers(T // 4, T, size=n_flips))
        flip_back = rng.random(size=n_flips) < 0.5        # some flips revert later

        # --- forward simulate ---
        tokens = np.full(T, PAD_TOKEN, dtype=np.int64)
        source_idx = np.full(T, -1, dtype=np.int64)
        posterior = np.empty((T, K), dtype=np.float64)
        source_trust = np.empty((T, S), dtype=np.float64)
        natural_len = int(rng.integers(T // 2, T + 1))      # varied length, then padded

        prior = np.full(K, 1.0 / K)
        r_current = r.copy()
        # schedule: (step, src, target_reliability)
        flip_schedule = []
        for idx, (src, step) in enumerate(zip(flip_srcs, flip_steps)):
            flip_schedule.append((step, int(src), 1.0 - r[src]))
            if flip_back[idx]:
                back_step = step + int(rng.integers(T // 8, T // 4))
                if back_step < T:
                    flip_schedule.append((back_step, int(src), r[src]))
        flip_schedule.sort()

        fi = 0
        for t in range(natural_len):
            while fi < len(flip_schedule) and flip_schedule[fi][0] <= t:
                _, fsrc, ftarget = flip_schedule[fi]
                r_current[fsrc] = ftarget
                fi += 1
            s_t = int(rng.integers(S))
            source_idx[t] = s_t
            source_trust[t] = r_current
            informative = rng.random() < r_current[s_t]
            if informative:
                tok_dist = L[:, h_star]
            else:
                tok_dist = marginal
            tok = int(rng.choice(info_vocab, p=tok_dist)) + 1
            tokens[t] = tok

            # Bayesian update on the OBSERVED token and source trust.
            likelihood = (
                r_current[s_t] * L[tok - 1]
                + (1.0 - r_current[s_t]) * marginal[tok - 1]
            )
            post = prior * likelihood
            post = post / post.sum()
            posterior[t] = post
            prior = post

        # pad the tail; carry the final posterior forward (no new evidence).
        if natural_len < T:
            tokens[natural_len:] = PAD_TOKEN
            posterior[natural_len:] = posterior[natural_len - 1]
            source_trust[natural_len:] = r_current

        # --- derive latents ---
        topmass = posterior.max(axis=1)
        log_posterior = np.zeros_like(posterior)
        np.log(posterior, out=log_posterior, where=posterior > 0)
        entropy = -(posterior * log_posterior).sum(axis=1)

        d_conf = np.zeros(T)
        d_conf[1:] = topmass[1:] - topmass[:-1]
        dd_conf = np.zeros(T)
        dd_conf[2:] = topmass[2:] - 2 * topmass[1:-1] + topmass[:-2]

        # decisive steps: those whose absolute belief move exceeds a fixed
        # threshold (not a quantile of survivors). A move of 0.02 on topmass
        # is a real shift in belief; below that is noise. This gives a stable,
        # comparable count across streams rather than a brittle top-k%.
        decisive_threshold = 0.02
        decisive_idx = (np.abs(d_conf) >= decisive_threshold).astype(np.int64)

        # block boundaries: contiguous, size = block_size
        block_size = max(1, T // 16)
        num_blocks = (T + block_size - 1) // block_size
        block_boundaries = np.concatenate([
            np.arange(0, T, block_size), [T]
        ]).astype(np.int64)

        return StreamSample(
            tokens=tokens,
            answer=int(posterior[-1].argmax()),
            posterior=posterior,
            entropy=entropy,
            belief_move=d_conf.copy(),
            d_conf=d_conf,
            dd_conf=dd_conf,
            source_idx=source_idx,
            source_trust=source_trust,
            decisive_idx=decisive_idx,
            block_boundaries=block_boundaries,
            metadata={
                "h_star": h_star,
                "reliability_init": r.tolist(),
                "flip_srcs": [int(x) for x in flip_srcs],
                "flip_steps": [int(x) for x in flip_steps],
                "flip_back": [bool(x) for x in flip_back],
                "natural_len": natural_len,
                "block_size": block_size,
            },
        )
